Updated matplotlib to 3.9.0 due to seaborn dependency issue
import seaborn as sns
File "/opt/venv/lib/python3.10/site-packages/seaborn/__init__.py", line 9, in <module>
from .matrix import * # noqa: F401,F403
File "/opt/venv/lib/python3.10/site-packages/seaborn/matrix.py", line 12, in <module>
from . import cm
File "/opt/venv/lib/python3.10/site-packages/seaborn/cm.py", line 1582, in <module>
mpl_cm.register_cmap(_name, _cmap)
AttributeError: module 'matplotlib.cm' has no attribute 'register_cmap'